### ISSUE TITLE
query string parse/stringify

### ISSUE THREAD

**Issue by bkniffler** [cellog/ion-router#15]
Hey,
There were always 2 major painpoints with react router v4:
- No native redux integration
- Query strings stripped away

ion-router seems really cool, but queries are not mentioned anywhere. Any possibility to use them, and how? Could we have some parseQuery and stringifyQuery methods to adapt the functionality?

Thanks, keep it up!

**Comment by cellog** [comment]
Thanks for taking the time to ask! ion-router uses route-parser internally (https://github.com/rcs/route-parser) which allows parsing query strings. However, it does not support generic queries out of order. You can implement this by providing several routes to match that have the path with the various permutations, of course. 

One of ion-router's initial design decisions was based around the idea that urls the user gets are either copied from the browser, shared on a phone, and never entered manually. Thus, your app can control the order of query params easily. 

If this is not enough control, you can also implement query string parsing inside stateFromParams. I'm on my phone so this will be a bit rough, but something like:

```js
const route = {
 name: 'queryroute', 
 path: '/something/:param?*query', 
 stateFromParams: params => {
  const queryParams = fancyParse(params.query)
  return {
   param: params.param,
   ...queryParams
 },
 paramsFromState: state => {
  return {
   query: makeQueryStringFromState(state), 
   param: state.something.param
  } 
 },
 // and updateState and/or exitParams here 
} 
```

So this would only be necessary if you need to support random ordering of query string, or something like PHP array syntax for a legacy app. 

For new apps, I highly recommend simply using a splat to put array elements into a defined subset of the path instead of using query strings. I've been using that with great success in an app I wrote which is using ion-router in production. 

If you have any specific scenario in mind that could help me understand a hole in the above design decisions, I would love to hear about it. 

Glad you decided to take a look at ion-router! There are several redux-first routers to choose from now, but I am partial to this one because it is the only one with simple reverse routing. Others have other advantages that may address your needs better, so definitely check them out too! 

Let me know if I can help out more.

**Comment by bkniffler** [comment]
Thanks for the explanations! Works good :)
